export const mountainData: any[] = [
  // ===== 五岳 =====
  {
    name: "华山", province: "陕西", elevation: 2154, category: "五岳",
    ticketPrice: 160, difficulty: "困难", duration: "1-2日",
    description: "西岳华山，以险峻著称，是五岳中海拔最高的山峰。自古有「奇险天下第一山」之说。",
    highlights: ["长空栈道", "鹞子翻身", "云海日出", "苍龙岭", "华山论剑"],
    culturalBackground: "道教圣地，金庸小说中华山论剑的原型。全真派圣地之一。",
    bestMonths: {"4":5,"5":5,"6":4,"7":3,"8":3,"9":5,"10":5,"11":4,"12":2,"1":2,"2":2,"3":3},
    seasonNotes: "春秋最佳，夏季雷雨多注意安全，冬季可赏雪景但路滑。国庆期间极度拥挤。",
    routes: [
      {"name":"自古华山一条路（北峰上）","distance":"约10km","time":"4-6小时","difficulty":"困难","nodes":["玉泉院","千尺幢","百尺峡","北峰","苍龙岭","金锁关"]},
      {"name":"西峰索道上北峰索道下","distance":"约6km","time":"3-4小时","difficulty":"中等","nodes":["西峰索道","南峰","东峰","中峰","北峰","北峰索道"]},
      {"name":"夜爬华山","distance":"约10km","time":"5-7小时","difficulty":"困难","nodes":["玉泉院","北峰","东峰看日出"]}
    ],
    tips: {"equipment":["登山鞋","手套","头灯（夜爬）","防寒外套","充电宝"],"booking":"旺季需提前1-3天网上预约门票和索道票","forbidden":["火种","大型行李"],"emergency":"华山景区救援电话：0913-4360199","accessibility":"西峰/北峰均有索道，但步行段仍较陡"},
    foods: [{"name":"华山大刀面","place":"玉泉院附近","price":"15-25元","note":"华山特色面食"},{"name":"华阴老腔火锅","place":"华阴市区","price":"60-100元/人","note":"边看老腔表演边吃火锅"}],
    transport: {"nearestAirport":"西安咸阳国际机场（约120km）","nearestStation":"华山北站（高铁）","fromBeijing":"高铁约5小时","fromShanghai":"高铁约6小时","fromGuangzhou":"高铁约8小时"},
    photoSpots: ["东峰日出观景台","长空栈道", "南峰绝顶","鹞子翻身"],
    latitude: "34.4870", longitude: "110.0849", imageUrl: "/mountains/huashan.jpg"
  },
  {
    name: "衡山", province: "湖南", elevation: 1300, category: "五岳",
    ticketPrice: 110, difficulty: "中等", duration: "1日",
    description: "南岳衡山，五岳之中最为秀丽，有「五岳独秀」之美誉。以壮美的日出、奇特的云海和佛道共存闻名。",
    highlights: ["祝融峰日出", "藏经殿", "南岳大庙", "磨镜台", "云海"],
    culturalBackground: "佛道共存的宗教圣地，南岳大庙是中国南方最大的古建筑群之一。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季炎热多雨，冬季可赏雾凇。",
    routes: [{"name":"中心景区步行","distance":"约14km","time":"5-6小时","difficulty":"中等","nodes":["南岳大庙","半山亭","南天门","祝融峰"]}],
    tips: {"equipment":["运动鞋","防晒","雨具"],"booking":"旺季建议提前预约","forbidden":["景区外香烛"],"emergency":"景区电话：0734-5673377","accessibility":"有环保车和索道可达半山"},
    foods: [{"name":"南岳素斋","place":"南岳大庙附近","price":"30-50元","note":"寺庙素食，清淡可口"},{"name":"衡山豆腐","place":"南岳镇","price":"15-25元","note":"当地特色"}],
    transport: {"nearestAirport":"长沙黄花国际机场（约150km）","nearestStation":"衡山西站（高铁）","fromBeijing":"高铁约6小时","fromShanghai":"高铁约5小时","fromGuangzhou":"高铁约3小时"},
    photoSpots: ["祝融峰顶", "望月台", "雾凇观景处"],
    latitude: "27.2543", longitude: "112.6552", imageUrl: "/mountains/hengshan.jpg"
  },
  {
    name: "嵩山", province: "河南", elevation: 1491, category: "五岳",
    ticketPrice: 80, difficulty: "中等", duration: "1日",
    description: "中岳嵩山，地处中原，文化底蕴深厚，是少林寺所在地。",
    highlights: ["少林寺", "嵩阳书院", "三皇寨", "连天栈道", "日出"],
    culturalBackground: "少林武术发源地，儒释道三教汇集之地，嵩阳书院为中国四大书院之一。",
    bestMonths: {"4":5,"5":5,"6":3,"7":2,"8":2,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋登山最佳，夏季炎热，冬季寒冷。",
    routes: [{"name":"太室山登顶","distance":"约12km","time":"5-6小时","difficulty":"中等","nodes":["嵩阳书院","老母洞","峻极峰"]},{"name":"少林寺+三皇寨","distance":"约10km","time":"4-5小时","difficulty":"中等","nodes":["少林寺","索道","三皇寨","吊桥"]}],
    tips: {"equipment":["运动鞋","防晒","饮用水"],"booking":"少林寺旺季限流，建议提前预约","forbidden":["无人机"],"emergency":"景区电话：0371-62745000","accessibility":"少林寺有索道至三皇寨"},
    foods: [{"name":"登封烩面","place":"登封市区","price":"15-20元","note":"河南特色烩面"},{"name":"少林素饼","place":"少林寺景区","price":"10-20元","note":"少林寺特色糕点"}],
    transport: {"nearestAirport":"郑州新郑国际机场（约90km）","nearestStation":"郑州东站","fromBeijing":"高铁约3小时到郑州","fromShanghai":"高铁约4小时到郑州","fromGuangzhou":"高铁约5.5小时到郑州"},
    photoSpots: ["峻极峰顶", "三皇寨栈道", "少林寺山门"],
    latitude: "34.4589", longitude: "112.9946", imageUrl: "/mountains/songshan.jpg"
  },
  {
    name: "恒山", province: "山西", elevation: 2016, category: "五岳",
    ticketPrice: 45, difficulty: "简单", duration: "1日",
    description: "北岳恒山，塞外第一名山，以悬空寺闻名天下。",
    highlights: ["悬空寺", "天峰岭", "恒山松", "恒宗殿", "云海"],
    culturalBackground: "道教圣地，悬空寺是中国仅存的佛道儒三教合一的独特寺庙。",
    bestMonths: {"5":5,"6":5,"7":4,"8":4,"9":5,"10":4,"4":4,"11":2,"3":3,"12":1,"1":1,"2":1},
    seasonNotes: "夏秋最佳，冬季极寒（-20°C以下），部分区域封山。",
    routes: [{"name":"主峰天峰岭","distance":"约6km","time":"3-4小时","difficulty":"简单","nodes":["停车场","恒宗殿","天峰岭"]}],
    tips: {"equipment":["保暖衣物","运动鞋"],"booking":"悬空寺限流100人，需单独购票","forbidden":[],"emergency":"景区电话：0352-8322142","accessibility":"台阶较多但坡度不大"},
    foods: [{"name":"浑源凉粉","place":"浑源县","price":"8-12元","note":"山西名小吃"},{"name":"莜面栲栳栳","place":"浑源县","price":"15-20元","note":"山西特色面食"}],
    transport: {"nearestAirport":"大同云冈机场（约80km）","nearestStation":"大同南站（高铁）","fromBeijing":"高铁约2小时到大同","fromShanghai":"高铁约7小时到大同","fromGuangzhou":"飞机约3小时到大同"},
    photoSpots: ["悬空寺全景", "天峰岭日出"],
    latitude: "39.6757", longitude: "113.7397", imageUrl: "/mountains/hengshan-north.jpg"
  },
  {
    name: "泰山", province: "山东", elevation: 1545, category: "五岳",
    ticketPrice: 115, difficulty: "中等", duration: "1-2日",
    description: "东岳泰山，五岳之首，被誉为「天下第一山」。自古帝王封禅之地。",
    highlights: ["玉皇顶日出", "十八盘", "南天门", "碧霞祠", "石刻"],
    culturalBackground: "中国历史上第一个被联合国教科文组织认定的自然与文化双遗产。帝王封禅圣地。",
    bestMonths: {"4":5,"5":5,"6":4,"7":3,"8":3,"9":5,"10":5,"11":3,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季多雷雨，冬季可赏雾凇但极冷。国庆拥挤。",
    routes: [{"name":"红门经典步行路线","distance":"约9km","time":"4-6小时","difficulty":"中等","nodes":["红门","中天门","十八盘","南天门","玉皇顶"]},{"name":"天外村车+索道","distance":"约3km步行","time":"2-3小时","difficulty":"简单","nodes":["天外村","中天门","索道","南天门","玉皇顶"]},{"name":"夜爬看日出","distance":"约9km","time":"5-7小时","difficulty":"中等","nodes":["红门","夜间登山","玉皇顶日出"]}],
    tips: {"equipment":["登山鞋","保暖衣物","头灯（夜爬）","手套"],"booking":"旺季需提前预约","forbidden":["明火"],"emergency":"景区救援电话：0538-8066166","accessibility":"有客车至中天门，索道至南天门"},
    foods: [{"name":"泰山煎饼","place":"泰山脚下","price":"5-10元","note":"山东名小吃"},{"name":"泰安豆腐宴","place":"泰安市区","price":"50-80元/人","note":"泰山特色宴席"}],
    transport: {"nearestAirport":"济南遥墙国际机场（约80km）","nearestStation":"泰安站（高铁）","fromBeijing":"高铁约2小时","fromShanghai":"高铁约3.5小时","fromGuangzhou":"高铁约7小时"},
    photoSpots: ["玉皇顶观日出", "十八盘仰望南天门", "五大夫松"],
    latitude: "36.2563", longitude: "117.1009", imageUrl: "/mountains/taishan.jpg"
  },
  // ===== 五大佛教名山 =====
  {
    name: "峨眉山", province: "四川", elevation: 3099, category: "佛教名山",
    ticketPrice: 160, difficulty: "困难", duration: "2-3日",
    description: "中国四大佛教名山之一，普贤菩萨道场，世界文化与自然遗产。",
    highlights: ["金顶日出", "云海", "佛光", "万年寺", "猴区", "冰雪"],
    culturalBackground: "普贤菩萨道场，中国佛教四大名山之一，有「峨眉天下秀」之称。",
    bestMonths: {"4":4,"5":5,"6":4,"7":3,"8":3,"9":5,"10":5,"11":4,"3":3,"12":3,"1":2,"2":2},
    seasonNotes: "春秋最佳，冬季金顶雪景壮观。夏季山下酷热但山顶凉爽。",
    routes: [{"name":"全程步行登顶","distance":"约50km","time":"2-3天","difficulty":"困难","nodes":["报国寺","清音阁","猴区","洗象池","雷洞坪","金顶"]},{"name":"半程步行+索道","distance":"约15km","time":"1-2天","difficulty":"中等","nodes":["报国寺","万年寺索道","华严顶","雷洞坪","金顶索道"]}],
    tips: {"equipment":["登山杖","防雨衣","保暖衣物","防猴棍（景区提供）"],"booking":"金顶索道旺季需提前购买","forbidden":["挑逗猴子","食物外露"],"emergency":"景区电话：0833-5590998","accessibility":"有观光车和索道"},
    foods: [{"name":"峨眉豆腐脑","place":"报国寺附近","price":"8-15元","note":"当地早餐"},{"name":"钵钵鸡","place":"峨眉山市","price":"30-50元","note":"四川名小吃"}],
    transport: {"nearestAirport":"成都双流国际机场（约150km）","nearestStation":"峨眉山站（高铁）","fromBeijing":"飞机约3小时到成都","fromShanghai":"飞机约3小时到成都","fromGuangzhou":"飞机约2.5小时到成都"},
    photoSpots: ["金顶日出", "云海佛光", "清音阁双桥"],
    latitude: "29.5220", longitude: "103.3387", imageUrl: "/mountains/emeishan.jpg"
  },
  {
    name: "五台山", province: "山西", elevation: 3061, category: "佛教名山",
    ticketPrice: 135, difficulty: "中等", duration: "2日",
    description: "中国佛教四大名山之首，文殊菩萨道场，世界文化遗产。",
    highlights: ["大白塔", "菩萨顶", "显通寺", "东台日出", "高山草甸"],
    culturalBackground: "文殊菩萨道场，中国唯一青庙黄庙并存的佛教圣地。",
    bestMonths: {"6":5,"7":5,"8":5,"9":4,"5":4,"10":3,"4":3,"11":1,"3":1,"12":1,"1":1,"2":1},
    seasonNotes: "夏季最佳（避暑胜地），冬季极寒多封山，海拔高注意高反。",
    routes: [{"name":"朝台（大朝台）","distance":"约70km","time":"2-3天","difficulty":"困难","nodes":["东台→北台→中台→西台→南台"]},{"name":"核心寺庙群","distance":"约5km","time":"1天","difficulty":"简单","nodes":["显通寺","菩萨顶","塔院寺","殊像寺"]}],
    tips: {"equipment":["保暖衣物（即使夏天）","防晒","登山鞋"],"booking":"进入核心景区需购票","forbidden":["景区内开车需另购票"],"emergency":"景区电话：0350-6548690","accessibility":"核心区可乘坐景区巴士"},
    foods: [{"name":"五台山素斋","place":"寺庙区","price":"20-40元","note":"佛教素食"},{"name":"台蘑炖鸡","place":"台怀镇","price":"60-80元","note":"五台山特产蘑菇"}],
    transport: {"nearestAirport":"太原武宿机场（约240km）","nearestStation":"五台山站","fromBeijing":"火车约5小时","fromShanghai":"飞机约2.5小时到太原","fromGuangzhou":"飞机约3小时到太原"},
    photoSpots: ["东台望海峰日出", "大白塔", "菩萨顶俯瞰"],
    latitude: "39.0768", longitude: "113.5933", imageUrl: "/mountains/wutaishan.jpg"
  },
  {
    name: "九华山", province: "安徽", elevation: 1342, category: "佛教名山",
    ticketPrice: 160, difficulty: "中等", duration: "1-2日",
    description: "地藏菩萨道场，中国佛教四大名山之一。",
    highlights: ["天台正顶", "肉身宝殿", "百岁宫", "凤凰松", "云海"],
    culturalBackground: "地藏菩萨道场，以「地狱未空，誓不成佛」精神闻名。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季多雨潮湿，冬季较冷。",
    routes: [{"name":"天台景区","distance":"约8km","time":"4-5小时","difficulty":"中等","nodes":["凤凰松","古拜经台","天台正顶"]},{"name":"花台景区","distance":"约6km","time":"3-4小时","difficulty":"中等","nodes":["花台索道","天门","花台"]}],
    tips: {"equipment":["运动鞋","雨具","香烛可景区购买"],"booking":"旺季建议提前预约","forbidden":["荤食（部分区域）"],"emergency":"景区电话：0566-2823169","accessibility":"有索道到百岁宫和天台"},
    foods: [{"name":"九华素饼","place":"九华街","price":"10-20元","note":"当地特色糕点"},{"name":"石耳炖鸡","place":"九华山镇","price":"50-80元","note":"九华山特产"}],
    transport: {"nearestAirport":"池州九华山机场（约40km）","nearestStation":"池州站（高铁）","fromBeijing":"高铁约5小时","fromShanghai":"高铁约3小时","fromGuangzhou":"高铁约7小时"},
    photoSpots: ["天台正顶日出", "百岁宫远眺", "凤凰松"],
    latitude: "30.4777", longitude: "117.8035", imageUrl: "/mountains/jiuhuashan.jpg"
  },
  {
    name: "雪窦山", province: "浙江", elevation: 800, category: "佛教名山",
    ticketPrice: 150, difficulty: "简单", duration: "1日",
    description: "弥勒佛道场，中国五大佛教名山之一。",
    highlights: ["雪窦寺", "千丈岩瀑布", "妙高台", "弥勒大佛", "张学良幽禁地"],
    culturalBackground: "弥勒佛道场，2005年被认定为中国第五大佛教名山。蒋介石故里。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季凉爽宜人。",
    routes: [{"name":"核心景区游览","distance":"约5km","time":"3-4小时","difficulty":"简单","nodes":["游客中心","千丈岩","雪窦寺","弥勒大佛"]}],
    tips: {"equipment":["轻便运动鞋","防晒"],"booking":"可现场购票","forbidden":[],"emergency":"景区电话：0574-88850077","accessibility":"景区交通便利，有观光车"},
    foods: [{"name":"奉化芋艿头","place":"溪口镇","price":"20-30元","note":"宁波名菜"},{"name":"千层饼","place":"溪口镇","price":"10-15元","note":"溪口特产"}],
    transport: {"nearestAirport":"宁波栎社机场（约30km）","nearestStation":"宁波站","fromBeijing":"飞机约2.5小时","fromShanghai":"高铁约2小时到宁波","fromGuangzhou":"飞机约2.5小时"},
    photoSpots: ["千丈岩瀑布", "弥勒大佛", "妙高台"],
    latitude: "29.7800", longitude: "121.4700", imageUrl: "/mountains/xuedoushan.jpg"
  },
  {
    name: "普陀山", province: "浙江", elevation: 291, category: "佛教名山",
    ticketPrice: 160, difficulty: "简单", duration: "1-2日",
    description: "观音菩萨道场，中国四大佛教名山之一，海天佛国。",
    highlights: ["南海观音大佛", "普济寺", "法雨寺", "佛顶山", "千步沙"],
    culturalBackground: "观音菩萨道场，有「海天佛国」之称，是中国最著名的海岛佛教圣地。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季台风季注意天气。观音诞辰（农历二月十九、六月十九、九月十九）人极多。",
    routes: [{"name":"一日精华线","distance":"约8km","time":"1天","difficulty":"简单","nodes":["码头","普济寺","法雨寺","佛顶山","南海观音"]}],
    tips: {"equipment":["防晒","舒适鞋","雨伞"],"booking":"船票旺季需提前预约","forbidden":["荤食（建议）"],"emergency":"景区电话：0580-6091414","accessibility":"岛上有小巴和观光车"},
    foods: [{"name":"普陀素斋","place":"寺庙区","price":"20-40元","note":"佛教素食"},{"name":"海鲜面","place":"码头附近","price":"30-60元","note":"舟山海鲜"}],
    transport: {"nearestAirport":"舟山普陀山机场","nearestStation":"宁波站（转船）","fromBeijing":"飞机约2.5小时到宁波","fromShanghai":"高铁约2小时到宁波再转船","fromGuangzhou":"飞机约3小时"},
    photoSpots: ["南海观音日落", "千步沙", "佛顶山俯瞰"],
    latitude: "30.0098", longitude: "122.3868", imageUrl: "/mountains/putuoshan.jpg"
  },
  // ===== 徒步名山 =====
  {
    name: "梅里雪山", province: "云南", elevation: 6740, category: "徒步",
    ticketPrice: 40, difficulty: "专业", duration: "3-5日",
    description: "藏区八大神山之首，至今无人登顶。雨崩徒步是中国最经典的徒步路线之一。",
    highlights: ["日照金山", "雨崩冰湖", "神瀑", "明永冰川", "飞来寺"],
    culturalBackground: "藏传佛教圣山，藏族人心中最神圣的山峰，禁止攀登主峰。",
    bestMonths: {"10":5,"11":5,"12":4,"1":4,"2":3,"3":3,"4":3,"5":3,"6":2,"7":1,"8":1,"9":2},
    seasonNotes: "10-11月最佳（看日照金山概率最高），雨季（6-9月）不建议前往。",
    routes: [{"name":"雨崩徒步（内外转）","distance":"约70km","time":"4-5天","difficulty":"专业","nodes":["西当→南宗垭口→上雨崩→冰湖→下雨崩→神瀑→尼农出"]},{"name":"飞来寺观景","distance":"约2km","time":"半天","difficulty":"简单","nodes":["飞来寺观景台"]}],
    tips: {"equipment":["专业登山鞋","登山杖","羽绒服","防水冲锋衣","高反药物"],"booking":"雨崩需购买门票","forbidden":["攀登主峰（被永久禁止）"],"emergency":"迪庆藏族自治州救援","accessibility":"进入雨崩需徒步或骑骡子"},
    foods: [{"name":"酥油茶","place":"雨崩村","price":"10-15元","note":"藏族传统饮品"},{"name":"青稞饼","place":"雨崩村","price":"5-10元","note":"藏区主食"}],
    transport: {"nearestAirport":"迪庆香格里拉机场（约180km）","nearestStation":"丽江站（火车）","fromBeijing":"飞机约4小时到丽江","fromShanghai":"飞机约4小时到丽江","fromGuangzhou":"飞机约3小时到丽江"},
    photoSpots: ["飞来寺日照金山", "冰湖", "雨崩村"],
    latitude: "28.4333", longitude: "98.6833", imageUrl: "/mountains/meilixueshan.jpg"
  },
  {
    name: "四姑娘山", province: "四川", elevation: 6250, category: "徒步",
    ticketPrice: 150, difficulty: "困难", duration: "2-3日",
    description: "「蜀山之后」，四座连绵的山峰如四位美丽少女。长坪沟和双桥沟是经典徒步目的地。",
    highlights: ["幺妹峰", "双桥沟", "长坪沟", "海子沟", "日出金山"],
    culturalBackground: "嘉绒藏族文化区域，四座山峰的传说充满了浪漫色彩。",
    bestMonths: {"5":4,"6":5,"7":4,"8":4,"9":5,"10":5,"11":3,"4":3,"3":2,"12":1,"1":1,"2":1},
    seasonNotes: "6-10月最佳，冬季大雪封山，海拔高注意高反。",
    routes: [{"name":"长坪沟徒步","distance":"约24km","time":"2天","difficulty":"困难","nodes":["喇嘛寺→枯树滩→木骡子营地"]},{"name":"双桥沟观光","distance":"约10km","time":"1天","difficulty":"简单","nodes":["观光车游览各景点"]}],
    tips: {"equipment":["登山鞋","羽绒服","登山杖","高反药"],"booking":"需提前预约","forbidden":["未经许可攀登三峰以上"],"emergency":"日隆镇救援站","accessibility":"双桥沟有观光车"},
    foods: [{"name":"牦牛肉火锅","place":"日隆镇","price":"80-120元/人","note":"高原特色"},{"name":"藏式糌粑","place":"日隆镇","price":"10-15元","note":"藏族传统食品"}],
    transport: {"nearestAirport":"成都双流国际机场（约230km）","nearestStation":"成都站","fromBeijing":"飞机约3小时到成都","fromShanghai":"飞机约3小时到成都","fromGuangzhou":"飞机约2.5小时到成都"},
    photoSpots: ["猫鼻梁观日出", "长坪沟", "双桥沟倒影"],
    latitude: "31.0900", longitude: "102.8800", imageUrl: "/mountains/siguniangshan.jpg"
  },
  {
    name: "武功山", province: "江西", elevation: 1918, category: "徒步",
    ticketPrice: 70, difficulty: "中等", duration: "2日",
    description: "以高山草甸和绝美日出闻名的徒步圣地，被称为「户外天堂」。",
    highlights: ["高山草甸", "云海日出", "帐篷节", "金顶", "吊马桩"],
    culturalBackground: "道教名山之一，山顶有白鹤峰道观遗址。",
    bestMonths: {"4":4,"5":5,"6":5,"7":3,"8":3,"9":5,"10":5,"11":3,"3":3,"12":1,"1":1,"2":1},
    seasonNotes: "5-6月和9-10月最佳（草甸最绿/秋色），帐篷节期间热闹。",
    routes: [{"name":"正门上（萍乡方向）","distance":"约12km","time":"5-7小时","difficulty":"中等","nodes":["石鼓寺→吊马桩→好汉坡→金顶"]},{"name":"反穿（明月山方向）","distance":"约20km","time":"2天","difficulty":"困难","nodes":["明月山→羊狮幕→发云界→金顶"]}],
    tips: {"equipment":["帐篷（山顶可租）","防风衣","登山杖","头灯"],"booking":"旺季门票需预约","forbidden":["野外用火"],"emergency":"景区电话：0799-7636666","accessibility":"有索道到金顶附近"},
    foods: [{"name":"萍乡炒粉","place":"萍乡市","price":"10-15元","note":"当地特色"},{"name":"莲花血鸭","place":"萍乡市","price":"40-60元","note":"江西名菜"}],
    transport: {"nearestAirport":"长沙黄花机场（约200km）","nearestStation":"萍乡北站（高铁）","fromBeijing":"高铁约6小时","fromShanghai":"高铁约5小时","fromGuangzhou":"高铁约4小时"},
    photoSpots: ["金顶日出", "高山草甸", "吊马桩云海"],
    latitude: "27.4617", longitude: "114.1585", imageUrl: "/mountains/wugongshan.jpg"
  },
  {
    name: "天柱山", province: "安徽", elevation: 1489, category: "徒步",
    ticketPrice: 130, difficulty: "中等", duration: "1日",
    description: "古南岳天柱山，以奇峰怪石闻名，国家地质公园。",
    highlights: ["天柱峰", "飞来石", "炼丹湖", "神秘谷", "石牛古洞"],
    culturalBackground: "古代南岳，汉武帝封禅之地，有深厚的道教和诗歌文化。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":2,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季可避暑。",
    routes: [{"name":"主峰景区","distance":"约10km","time":"5-6小时","difficulty":"中等","nodes":["大龙窝→振衣岗→神秘谷→天池峰→天柱峰（远观）"]}],
    tips: {"equipment":["登山鞋","防晒","饮用水"],"booking":"可现场购票","forbidden":[],"emergency":"景区电话：0556-8146588","accessibility":"有索道至振衣岗"},
    foods: [{"name":"天柱山瓦罐汤","place":"潜山市","price":"15-25元","note":"安徽特色"},{"name":"潜山板栗","place":"景区周边","price":"10-15元","note":"当地土特产"}],
    transport: {"nearestAirport":"合肥新桥机场（约180km）","nearestStation":"天柱山站","fromBeijing":"高铁约5小时","fromShanghai":"高铁约4小时","fromGuangzhou":"高铁约7小时"},
    photoSpots: ["天柱峰远眺", "飞来石", "炼丹湖"],
    latitude: "30.7439", longitude: "116.4392", imageUrl: "/mountains/tianzhushan.jpg"
  },
  {
    name: "长白山", province: "吉林", elevation: 2691, category: "徒步",
    ticketPrice: 190, difficulty: "中等", duration: "1-2日",
    description: "东北第一高峰，以天池闻名于世。冬季是滑雪胜地。",
    highlights: ["天池", "长白瀑布", "地下森林", "温泉煮蛋", "高山花园"],
    culturalBackground: "满族圣山，被称为「长白仙境」。中朝界山。",
    bestMonths: {"7":5,"8":5,"9":4,"6":4,"10":3,"5":3,"1":3,"2":3,"12":3,"11":2,"4":2,"3":2},
    seasonNotes: "7-8月最佳（天池开放率最高），冬季可滑雪泡温泉。天池开放取决于天气。",
    routes: [{"name":"北坡（经典线路）","distance":"约5km","time":"3-4小时","difficulty":"中等","nodes":["环保车→倒站车→天池→长白瀑布→地下森林"]},{"name":"西坡","distance":"约3km","time":"2-3小时","difficulty":"中等","nodes":["环保车→1442级台阶→天池西侧"]}],
    tips: {"equipment":["防风防雨外套","保暖衣物","防晒"],"booking":"旺季必须提前网上预约门票和车票","forbidden":["下到天池水边"],"emergency":"景区电话：0433-5742286","accessibility":"有环保车和倒站车"},
    foods: [{"name":"朝鲜冷面","place":"二道白河镇","price":"15-25元","note":"延边特色"},{"name":"温泉煮蛋","place":"长白山景区","price":"10元","note":"用火山温泉煮的鸡蛋"}],
    transport: {"nearestAirport":"长白山机场","nearestStation":"安图西站（高铁）","fromBeijing":"飞机约2.5小时","fromShanghai":"飞机约3小时","fromGuangzhou":"飞机约4小时"},
    photoSpots: ["天池全景", "长白瀑布", "高山花园"],
    latitude: "42.0030", longitude: "128.0600", imageUrl: "/mountains/changbaishan.jpg"
  },
  // ===== 四大道教名山 =====
  {
    name: "青城山", province: "四川", elevation: 1260, category: "道教名山",
    ticketPrice: 80, difficulty: "简单", duration: "1日",
    description: "中国道教发源地之一，「青城天下幽」。世界文化遗产。",
    highlights: ["天师洞", "上清宫", "老君阁", "幽深古道", "翠竹"],
    culturalBackground: "道教发源地，天师道创始人张道陵在此修炼。",
    bestMonths: {"3":5,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":3,"2":3},
    seasonNotes: "四季可游，春秋最佳，夏季避暑好去处。",
    routes: [{"name":"前山经典线","distance":"约8km","time":"3-4小时","difficulty":"简单","nodes":["山门→天师洞→上清宫→老君阁"]}],
    tips: {"equipment":["轻便运动鞋","雨伞","驱蚊水"],"booking":"可现场购票","forbidden":[],"emergency":"景区电话：028-87111907","accessibility":"有索道至上清宫"},
    foods: [{"name":"青城山老腊肉","place":"青城山镇","price":"40-60元","note":"当地名菜"},{"name":"白果炖鸡","place":"青城山镇","price":"50-80元","note":"道教养生菜"}],
    transport: {"nearestAirport":"成都双流机场（约68km）","nearestStation":"青城山站（高铁）","fromBeijing":"飞机约3小时到成都","fromShanghai":"飞机约3小时到成都","fromGuangzhou":"飞机约2.5小时到成都"},
    photoSpots: ["老君阁远眺", "天师洞", "幽静古道"],
    latitude: "30.8981", longitude: "103.5719", imageUrl: "/mountains/qingchengshan.jpg"
  },
  {
    name: "武当山", province: "湖北", elevation: 1612, category: "道教名山",
    ticketPrice: 240, difficulty: "中等", duration: "2日",
    description: "道教第一仙山，武当武术发源地。世界文化遗产。",
    highlights: ["金顶金殿", "紫霄宫", "南岩宫", "太子坡", "武当功夫"],
    culturalBackground: "道教第一仙山，真武大帝修炼之地，武当武术闻名天下。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":2,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季山上凉爽。",
    routes: [{"name":"全程游览","distance":"约20km","time":"2天","difficulty":"中等","nodes":["太子坡→紫霄宫→南岩宫→金顶"]},{"name":"索道快速游","distance":"约8km","time":"1天","difficulty":"简单","nodes":["太子坡→琼台索道→金顶→南岩宫"]}],
    tips: {"equipment":["登山鞋","保暖衣物","防晒"],"booking":"旺季建议提前购票","forbidden":["景区内私家车需换乘"],"emergency":"景区电话：0719-5668567","accessibility":"有景区巴士和索道"},
    foods: [{"name":"武当道茶","place":"景区","price":"30-60元","note":"道教养生茶"},{"name":"武当山豆腐","place":"武当山镇","price":"15-25元","note":"当地名菜"}],
    transport: {"nearestAirport":"武当山机场（约15km）","nearestStation":"武当山西站（高铁）","fromBeijing":"高铁约5小时","fromShanghai":"高铁约5小时","fromGuangzhou":"高铁约5小时"},
    photoSpots: ["金顶日出", "南岩龙头香", "紫霄宫"],
    latitude: "32.4000", longitude: "111.0044", imageUrl: "/mountains/wudangshan.jpg"
  },
  {
    name: "龙虎山", province: "江西", elevation: 247, category: "道教名山",
    ticketPrice: 165, difficulty: "简单", duration: "1日",
    description: "中国道教发祥地，丹霞地貌与道教文化交相辉映。世界自然遗产。",
    highlights: ["天师府", "悬棺表演", "竹筏漂流", "丹霞地貌", "象鼻山"],
    culturalBackground: "正一道发源地，张天师世居之地。因丹霞地貌入选世界自然遗产。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，夏季炎热，但竹筏漂流凉爽。",
    routes: [{"name":"精华一日游","distance":"约5km","time":"1天","difficulty":"简单","nodes":["天师府→竹筏漂流→悬棺表演→象鼻山"]}],
    tips: {"equipment":["防晒","舒适鞋","防水手机袋（漂流）"],"booking":"竹筏需提前预约","forbidden":[],"emergency":"景区电话：0701-6380088","accessibility":"景区较为平坦"},
    foods: [{"name":"天师板栗烧鸡","place":"龙虎山镇","price":"40-60元","note":"龙虎山名菜"},{"name":"上清豆腐","place":"上清古镇","price":"15-25元","note":"千年古镇美食"}],
    transport: {"nearestAirport":"南昌昌北机场（约130km）","nearestStation":"鹰潭站","fromBeijing":"高铁约6小时","fromShanghai":"高铁约3小时","fromGuangzhou":"高铁约5小时"},
    photoSpots: ["仙水岩丹霞", "象鼻山", "竹筏上"],
    latitude: "28.0820", longitude: "116.9500", imageUrl: "/mountains/longhushan.jpg"
  },
  {
    name: "齐云山", province: "安徽", elevation: 585, category: "道教名山",
    ticketPrice: 68, difficulty: "简单", duration: "1日",
    description: "中国四大道教名山之一，以道教文化和丹霞地貌闻名。",
    highlights: ["月华街", "太素宫", "玉虚宫", "方腊寨", "丹霞地貌"],
    culturalBackground: "道教名山，有「黄山白岳相对峙，绿水丹崖甲江南」之说。",
    bestMonths: {"3":5,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，四季可游。",
    routes: [{"name":"登山步道","distance":"约6km","time":"3-4小时","difficulty":"简单","nodes":["登封桥→望仙台→月华街→最高峰"]}],
    tips: {"equipment":["轻便运动鞋","防晒"],"booking":"可现场购票","forbidden":[],"emergency":"景区电话：0559-7560063","accessibility":"有索道至月华街"},
    foods: [{"name":"齐云山豆干","place":"月华街","price":"10-15元","note":"山上道士手工制作"},{"name":"徽州臭鳜鱼","place":"休宁县","price":"50-80元","note":"徽菜代表"}],
    transport: {"nearestAirport":"黄山屯溪机场（约30km）","nearestStation":"黄山北站（高铁）","fromBeijing":"高铁约6小时","fromShanghai":"高铁约3.5小时","fromGuangzhou":"高铁约7小时"},
    photoSpots: ["月华街晨雾", "丹霞日落"],
    latitude: "29.8000", longitude: "118.0500", imageUrl: "/mountains/qiyunshan.jpg"
  },
  // ===== 地貌/网红 =====
  {
    name: "太白山", province: "陕西", elevation: 3771, category: "地貌/网红",
    ticketPrice: 150, difficulty: "困难", duration: "2-3日",
    description: "秦岭主峰，陕西最高峰。南北气候分界线上的天然植物园。",
    highlights: ["大爷海", "拔仙台", "高山杜鹃", "第四纪冰川遗迹", "板寺新村云海"],
    culturalBackground: "传说太白金星修炼之地，秦岭核心区域，生物多样性极其丰富。",
    bestMonths: {"6":5,"7":5,"8":4,"9":5,"5":4,"10":3,"4":3,"11":1,"3":1,"12":1,"1":1,"2":1},
    seasonNotes: "6-9月最佳，其余时间山顶积雪。高海拔注意高反。",
    routes: [{"name":"南坡经典线","distance":"约30km","time":"2-3天","difficulty":"困难","nodes":["下板寺→大文公庙→大爷海→拔仙台"]}],
    tips: {"equipment":["登山鞋","羽绒服","登山杖","高反药"],"booking":"需提前预约","forbidden":["偏离标记路线"],"emergency":"景区电话：0917-5711682","accessibility":"有索道至下板寺"},
    foods: [{"name":"臊子面","place":"太白县","price":"15-20元","note":"陕西名面"},{"name":"搅团","place":"太白县","price":"10-15元","note":"当地特色面食"}],
    transport: {"nearestAirport":"西安咸阳机场（约150km）","nearestStation":"眉县站","fromBeijing":"高铁约5小时到西安","fromShanghai":"高铁约6小时到西安","fromGuangzhou":"高铁约8小时到西安"},
    photoSpots: ["大爷海", "拔仙台顶", "云海"],
    latitude: "33.9550", longitude: "107.7690", imageUrl: "/mountains/taibaishan.jpg"
  },
  {
    name: "梵净山", province: "贵州", elevation: 2572, category: "地貌/网红",
    ticketPrice: 120, difficulty: "中等", duration: "1日",
    description: "世界自然遗产，以蘑菇石和红云金顶闻名。中国十大避暑名山之一。",
    highlights: ["蘑菇石", "红云金顶", "万米睡佛", "珙桐花", "云海"],
    culturalBackground: "弥勒菩萨道场，梵天净土之意。",
    bestMonths: {"4":5,"5":5,"6":4,"7":3,"8":3,"9":5,"10":5,"11":3,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季雨多路滑，冬季山顶结冰。",
    routes: [{"name":"东门步行上山","distance":"约8km","time":"4-5小时","difficulty":"中等","nodes":["东门→万步云梯→蘑菇石→红云金顶"]}],
    tips: {"equipment":["登山鞋","雨衣","手套"],"booking":"必须提前网上预约门票和索道","forbidden":["无预约不得进入"],"emergency":"景区电话：0856-6720000","accessibility":"有索道至万宝岩"},
    foods: [{"name":"江口豆腐","place":"江口县","price":"15-25元","note":"贵州名菜"},{"name":"社饭","place":"江口县","price":"10-15元","note":"当地特色"}],
    transport: {"nearestAirport":"铜仁凤凰机场（约80km）","nearestStation":"铜仁南站（高铁）","fromBeijing":"飞机约3小时到铜仁","fromShanghai":"飞机约3小时到铜仁","fromGuangzhou":"高铁约5小时"},
    photoSpots: ["蘑菇石", "红云金顶", "万米睡佛"],
    latitude: "27.9100", longitude: "108.6800", imageUrl: "/mountains/fanjingshan.jpg"
  },
  {
    name: "张家界", province: "湖南", elevation: 1262, category: "地貌/网红",
    ticketPrice: 273, difficulty: "中等", duration: "2-3日",
    description: "世界自然遗产，《阿凡达》悬浮山原型。以石英砂岩峰林地貌闻名世界。",
    highlights: ["哈利路亚山", "天门山玻璃栈道", "百龙天梯", "金鞭溪", "天子山"],
    culturalBackground: "土家族苗族文化区域，电影《阿凡达》取景地。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季多雨但云海壮观，冬季雪景美但冷。",
    routes: [{"name":"国家森林公园2日游","distance":"约20km","time":"2天","difficulty":"中等","nodes":["金鞭溪→百龙天梯→袁家界→天子山→十里画廊"]},{"name":"天门山1日游","distance":"约5km","time":"1天","difficulty":"中等","nodes":["天门山索道→玻璃栈道→天门洞→盘山公路"]}],
    tips: {"equipment":["登山鞋","雨衣","防晒"],"booking":"旺季需提前预约","forbidden":[],"emergency":"景区电话：0744-5712189","accessibility":"百龙天梯+环保车，无障碍设施较好"},
    foods: [{"name":"三下锅","place":"张家界市区","price":"40-60元","note":"土家族名菜"},{"name":"血粑鸭","place":"张家界市区","price":"50-70元","note":"湘西特色"}],
    transport: {"nearestAirport":"张家界荷花机场","nearestStation":"张家界西站（高铁）","fromBeijing":"飞机约2.5小时","fromShanghai":"飞机约2.5小时","fromGuangzhou":"高铁约5小时"},
    photoSpots: ["哈利路亚山", "天门山", "天子山御笔峰"],
    latitude: "29.3257", longitude: "110.4340", imageUrl: "/mountains/zhangjiajie.jpg"
  },
  {
    name: "老君山", province: "河南", elevation: 2217, category: "地貌/网红",
    ticketPrice: 100, difficulty: "中等", duration: "1-2日",
    description: "道教圣地，近年因金顶道观群的壮美照片在社交媒体走红。",
    highlights: ["金顶道观群", "十里画屏", "马鬃岭", "日出云海", "追梦谷"],
    culturalBackground: "传说老子曾在此修炼，道教圣地之一。近年成为网红打卡地。",
    bestMonths: {"5":5,"6":4,"7":3,"8":3,"9":5,"10":5,"11":4,"4":4,"3":3,"12":2,"1":2,"2":2},
    seasonNotes: "5-6月和9-10月最佳，冬季雪景壮观但冷。",
    routes: [{"name":"索道+步行","distance":"约8km","time":"4-6小时","difficulty":"中等","nodes":["一级索道→二级索道→十里画屏→金顶"]},{"name":"全程步行","distance":"约15km","time":"6-8小时","difficulty":"困难","nodes":["山门→追梦谷→十里画屏→金顶"]}],
    tips: {"equipment":["登山鞋","保暖衣物","防风衣"],"booking":"旺季需提前网上购票","forbidden":[],"emergency":"景区电话：0379-66838888","accessibility":"两级索道可达山顶附近"},
    foods: [{"name":"栾川豆腐","place":"栾川县","price":"15-25元","note":"当地特色"},{"name":"山珍野味","place":"老君山镇","price":"50-80元","note":"山区特色菜"}],
    transport: {"nearestAirport":"洛阳北郊机场（约150km）","nearestStation":"洛阳龙门站（高铁）","fromBeijing":"高铁约4小时到洛阳","fromShanghai":"高铁约5小时到洛阳","fromGuangzhou":"高铁约6小时到洛阳"},
    photoSpots: ["金顶日出", "十里画屏", "云海"],
    latitude: "33.7561", longitude: "111.6408", imageUrl: "/mountains/laojunshan.jpg"
  },
  {
    name: "北疆石林", province: "新疆", elevation: 1200, category: "地貌/网红",
    ticketPrice: 120, difficulty: "简单", duration: "1日",
    description: "位于乌尔禾的雅丹地貌群，也称魔鬼城/乌尔禾风城，以独特的风蚀地貌闻名。",
    highlights: ["雅丹地貌", "日落金光", "恐龙化石", "风蚀城堡", "星空"],
    culturalBackground: "古丝绸之路北道，数亿年风蚀形成的地质奇观。",
    bestMonths: {"5":4,"6":5,"7":4,"8":4,"9":5,"10":4,"4":3,"11":2,"3":2,"12":1,"1":1,"2":1},
    seasonNotes: "5-10月最佳，日落时分最美。冬季极冷不建议。",
    routes: [{"name":"景区环线","distance":"约5km","time":"2-3小时","difficulty":"简单","nodes":["景区大门→小火车环游→步行观景"]}],
    tips: {"equipment":["防风沙装备","防晒","充足饮水"],"booking":"可现场购票","forbidden":["偏离路线（迷路风险）"],"emergency":"当地旅游部门","accessibility":"景区有小火车"},
    foods: [{"name":"大盘鸡","place":"克拉玛依","price":"50-80元","note":"新疆经典菜"},{"name":"烤羊肉串","place":"乌尔禾","price":"5-10元/串","note":"新疆特色"}],
    transport: {"nearestAirport":"克拉玛依机场（约100km）","nearestStation":"克拉玛依站","fromBeijing":"飞机约4小时","fromShanghai":"飞机约5小时","fromGuangzhou":"飞机约5小时"},
    photoSpots: ["日落时分风蚀城堡", "星空"],
    latitude: "46.0800", longitude: "84.7300", imageUrl: "/mountains/beijiangshilin.jpg"
  },
  {
    name: "云台山", province: "河南", elevation: 1308, category: "地貌/网红",
    ticketPrice: 120, difficulty: "中等", duration: "1-2日",
    description: "世界地质公园，红石峡是中国最美峡谷之一。",
    highlights: ["红石峡", "茱萸峰", "玻璃栈道", "潭瀑峡", "泉瀑峡"],
    culturalBackground: "竹林七贤隐居之地，王维「遍插茱萸少一人」的茱萸峰所在地。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季雨后瀑布壮观。",
    routes: [{"name":"精华一日游","distance":"约10km","time":"1天","difficulty":"中等","nodes":["红石峡→潭瀑峡→泉瀑峡"]},{"name":"二日全景游","distance":"约18km","time":"2天","difficulty":"中等","nodes":["红石峡→潭瀑峡→茱萸峰→万善寺"]}],
    tips: {"equipment":["防滑鞋","雨衣","防晒"],"booking":"旺季需预约","forbidden":[],"emergency":"景区电话：0391-7709300","accessibility":"景区巴士覆盖各景点"},
    foods: [{"name":"修武黑山羊","place":"修武县","price":"50-80元","note":"当地特色"},{"name":"焦作烩面","place":"焦作市","price":"15-20元","note":"河南名吃"}],
    transport: {"nearestAirport":"郑州新郑机场（约100km）","nearestStation":"修武西站（高铁）","fromBeijing":"高铁约3小时到郑州","fromShanghai":"高铁约4小时到郑州","fromGuangzhou":"高铁约5.5小时到郑州"},
    photoSpots: ["红石峡", "茱萸峰", "潭瀑峡"],
    latitude: "35.4306", longitude: "113.3844", imageUrl: "/mountains/yuntaishan.jpg"
  },
  {
    name: "太姥山", province: "福建", elevation: 917, category: "地貌/网红",
    ticketPrice: 140, difficulty: "中等", duration: "1日",
    description: "世界地质公园，以花岗岩峰林和海蚀洞穴闻名。",
    highlights: ["夫妻峰", "一线天", "九鲤朝天", "太姥娘娘殿", "乌龙峡"],
    culturalBackground: "传说太姥娘娘种蓝草制茶，是白茶的发源地。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":3,"2":3},
    seasonNotes: "春秋最佳，夏季沿海气候较为舒适。",
    routes: [{"name":"核心景区步行","distance":"约8km","time":"4-5小时","difficulty":"中等","nodes":["山门→一线天→夫妻峰→九鲤朝天→观海台"]}],
    tips: {"equipment":["运动鞋","防晒","饮水"],"booking":"可现场购票","forbidden":[],"emergency":"景区电话：0593-7677063","accessibility":"有索道可选"},
    foods: [{"name":"福鼎肉片","place":"福鼎市","price":"15-25元","note":"当地特色"},{"name":"白茶","place":"太姥山镇","price":"50-200元","note":"太姥山白茶原产地"}],
    transport: {"nearestAirport":"温州龙湾机场（约130km）","nearestStation":"太姥山站（动车）","fromBeijing":"飞机约2.5小时到温州","fromShanghai":"动车约4小时","fromGuangzhou":"飞机约2小时到温州"},
    photoSpots: ["夫妻峰日出", "一线天", "海上仙都"],
    latitude: "27.0800", longitude: "120.2300", imageUrl: "/mountains/tailaoshan.jpg"
  },
  {
    name: "武夷山", province: "福建", elevation: 2158, category: "地貌/网红",
    ticketPrice: 140, difficulty: "中等", duration: "2日",
    description: "世界文化与自然双遗产，以丹霞地貌和大红袍茶闻名世界。",
    highlights: ["九曲溪竹筏", "天游峰", "大红袍", "虎啸岩", "武夷宫"],
    culturalBackground: "朱熹理学发源地，大红袍母树所在地。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，梅雨季节多雨。",
    routes: [{"name":"经典两日游","distance":"约15km","time":"2天","difficulty":"中等","nodes":["D1:天游峰→桃源洞→九曲溪竹筏 D2:虎啸岩→一线天→大红袍景区"]}],
    tips: {"equipment":["运动鞋","雨衣","防晒"],"booking":"九曲溪竹筏需提前预约","forbidden":[],"emergency":"景区电话：0599-5131890","accessibility":"景区巴士覆盖各景点"},
    foods: [{"name":"大红袍","place":"武夷山","price":"100-500元/盒","note":"世界级名茶"},{"name":"岚谷熏鹅","place":"武夷山市","price":"40-60元","note":"当地名菜"}],
    transport: {"nearestAirport":"武夷山机场","nearestStation":"武夷山北站（高铁）","fromBeijing":"高铁约7小时","fromShanghai":"高铁约4小时","fromGuangzhou":"高铁约6小时"},
    photoSpots: ["天游峰俯瞰", "九曲溪竹筏", "大红袍茶园"],
    latitude: "27.7545", longitude: "118.0353", imageUrl: "/mountains/wuyishan.jpg"
  },
  {
    name: "三清山", province: "江西", elevation: 1819, category: "地貌/网红",
    ticketPrice: 120, difficulty: "中等", duration: "1-2日",
    description: "世界自然遗产，以花岗岩峰林和道教文化闻名，被誉为「西太平洋最美的花岗岩」。",
    highlights: ["巨蟒出山", "司春女神", "西海岸栈道", "阳光海岸", "三清宫"],
    culturalBackground: "道教名山，以玉京、玉虚、玉华三峰如三清（道教最高神）列坐而得名。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，冬季雪景但部分路段封闭。",
    routes: [{"name":"南清园+西海岸","distance":"约12km","time":"5-6小时","difficulty":"中等","nodes":["南清园→巨蟒出山→司春女神→西海岸栈道"]},{"name":"全山环线","distance":"约20km","time":"8-10小时","difficulty":"困难","nodes":["南清园→西海岸→阳光海岸→三清宫→玉京峰"]}],
    tips: {"equipment":["登山鞋","防风衣","充足饮水"],"booking":"旺季建议提前购票","forbidden":[],"emergency":"景区电话：0793-2407999","accessibility":"有索道"},
    foods: [{"name":"三清山野生石鸡","place":"三清山镇","price":"50-80元","note":"当地特色"},{"name":"上饶鸡腿","place":"上饶市","price":"5-10元","note":"江西名小吃"}],
    transport: {"nearestAirport":"上饶三清山机场（约70km）","nearestStation":"上饶站（高铁）","fromBeijing":"高铁约6小时","fromShanghai":"高铁约3小时","fromGuangzhou":"高铁约6小时"},
    photoSpots: ["巨蟒出山", "司春女神", "西海岸日落"],
    latitude: "28.9144", longitude: "118.0641", imageUrl: "/mountains/sanqingshan.jpg"
  },
  {
    name: "华东扇屏", province: "浙江", elevation: 523, category: "地貌/网红",
    ticketPrice: null, difficulty: "简单", duration: "半日",
    description: "近年社交媒体爆红的悬崖秋千和网红打卡点，以独特的扇形岩壁闻名。",
    highlights: ["扇形岩壁", "悬崖秋千", "网红打卡", "日落", "云海"],
    culturalBackground: "因社交媒体走红的新兴网红景点。",
    bestMonths: {"3":4,"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳。",
    routes: [{"name":"景区游览","distance":"约3km","time":"2-3小时","difficulty":"简单","nodes":["入口→扇屏观景台→悬崖秋千"]}],
    tips: {"equipment":["运动鞋","防晒"],"booking":"建议提前查看开放时间","forbidden":[],"emergency":"当地旅游部门","accessibility":"步道较为完善"},
    foods: [{"name":"当地农家菜","place":"景区周边","price":"30-50元","note":"浙江农家菜"}],
    transport: {"nearestAirport":"杭州萧山机场","nearestStation":"杭州东站","fromBeijing":"高铁约5小时到杭州","fromShanghai":"高铁约1小时到杭州","fromGuangzhou":"高铁约7小时到杭州"},
    photoSpots: ["扇形岩壁全景", "日落"],
    latitude: "30.2000", longitude: "119.5000", imageUrl: "/mountains/huadongshan.jpg"
  },
  {
    name: "雁荡山", province: "浙江", elevation: 1150, category: "地貌/网红",
    ticketPrice: 170, difficulty: "中等", duration: "1-2日",
    description: "以奇峰怪石、古洞石室、飞瀑流泉闻名的「东南第一山」。",
    highlights: ["灵峰夜景", "灵岩飞渡", "大龙湫瀑布", "方洞", "显胜门"],
    culturalBackground: "中国十大名山之一，有「海上名山、寰中绝胜」之誉。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":3,"1":2,"2":3},
    seasonNotes: "春秋最佳，灵峰夜景四季可赏。",
    routes: [{"name":"精华一日游","distance":"约10km","time":"1天","difficulty":"中等","nodes":["灵峰景区→灵岩景区→大龙湫景区"]}],
    tips: {"equipment":["运动鞋","手电筒（夜景）","雨具"],"booking":"联票含三大景区","forbidden":[],"emergency":"景区电话：0577-62243217","accessibility":"部分景区有电瓶车"},
    foods: [{"name":"乐清湾海鲜","place":"雁荡镇","price":"50-100元","note":"东海海鲜"},{"name":"番薯粉丝汤","place":"雁荡镇","price":"10-15元","note":"当地特色小吃"}],
    transport: {"nearestAirport":"温州龙湾机场（约80km）","nearestStation":"雁荡山站（动车）","fromBeijing":"飞机约2.5小时到温州","fromShanghai":"动车约4小时","fromGuangzhou":"飞机约2小时到温州"},
    photoSpots: ["灵峰夜景", "灵岩飞渡", "大龙湫瀑布"],
    latitude: "28.3843", longitude: "121.0690", imageUrl: "/mountains/yandangshan.jpg"
  },
  {
    name: "黄山", province: "安徽", elevation: 1864, category: "地貌/网红",
    ticketPrice: 190, difficulty: "中等", duration: "2日",
    description: "「五岳归来不看山，黄山归来不看岳」。世界文化与自然双遗产。",
    highlights: ["迎客松", "云海", "奇松怪石", "温泉", "日出", "西海大峡谷"],
    culturalBackground: "中国最著名的风景名山，徐霞客赞「薄海内外无如徽之黄山」。",
    bestMonths: {"4":5,"5":5,"6":3,"7":3,"8":3,"9":5,"10":5,"11":4,"3":4,"12":3,"1":3,"2":3},
    seasonNotes: "春秋最佳赏云海，冬季雪景独特。国庆极其拥挤。",
    routes: [{"name":"前山上后山下","distance":"约15km","time":"1-2天","difficulty":"中等","nodes":["慈光阁→迎客松→天都峰→光明顶→飞来石→西海大峡谷→白鹅岭"]},{"name":"后山上前山下","distance":"约15km","time":"1-2天","difficulty":"中等","nodes":["云谷寺→白鹅岭→北海→光明顶→迎客松→慈光阁"]}],
    tips: {"equipment":["登山鞋","雨衣","保暖衣","登山杖"],"booking":"旺季必须提前预约门票和索道","forbidden":["吸烟（部分区域）"],"emergency":"景区电话：0559-5580327","accessibility":"有两条索道"},
    foods: [{"name":"毛豆腐","place":"汤口镇","price":"15-25元","note":"徽菜名品"},{"name":"臭鳜鱼","place":"汤口镇","price":"60-100元","note":"徽菜代表"}],
    transport: {"nearestAirport":"黄山屯溪机场","nearestStation":"黄山北站（高铁）","fromBeijing":"高铁约6小时","fromShanghai":"高铁约3小时","fromGuangzhou":"高铁约7小时"},
    photoSpots: ["光明顶日出", "迎客松", "西海大峡谷", "飞来石"],
    latitude: "30.1373", longitude: "118.1693", imageUrl: "/mountains/huangshan.jpg"
  },
  {
    name: "庐山", province: "江西", elevation: 1474, category: "地貌/网红",
    ticketPrice: 160, difficulty: "中等", duration: "2日",
    description: "世界文化遗产，中国四大避暑胜地之一。「不识庐山真面目」千古名句的出处。",
    highlights: ["三叠泉", "五老峰", "含鄱口", "花径", "锦绣谷", "仙人洞"],
    culturalBackground: "文化名山，白居易、苏轼、李白等无数文人留下诗篇。近代政治历史重地。",
    bestMonths: {"4":5,"5":5,"6":4,"7":4,"8":4,"9":5,"10":5,"11":4,"3":4,"12":2,"1":2,"2":2},
    seasonNotes: "春秋最佳，夏季避暑胜地（比山下低约10°C），冬季可赏雪。",
    routes: [{"name":"一线（西线）","distance":"约8km","time":"1天","difficulty":"简单","nodes":["花径→锦绣谷→仙人洞→大天池→龙首崖"]},{"name":"二线（东线）","distance":"约12km","time":"1天","difficulty":"中等","nodes":["含鄱口→五老峰→三叠泉"]}],
    tips: {"equipment":["运动鞋","雨具","薄外套"],"booking":"自驾需换乘景区大巴","forbidden":["景区内禁止自驾"],"emergency":"景区电话：0792-8296565","accessibility":"景区有观光车环线"},
    foods: [{"name":"庐山石鸡","place":"牯岭镇","price":"50-80元","note":"庐山名菜"},{"name":"庐山石鱼","place":"牯岭镇","price":"40-60元","note":"庐山三石之一"}],
    transport: {"nearestAirport":"九江庐山机场","nearestStation":"庐山站","fromBeijing":"高铁约5小时","fromShanghai":"高铁约4小时","fromGuangzhou":"高铁约5小时"},
    photoSpots: ["含鄱口日出", "三叠泉", "五老峰"],
    latitude: "29.5628", longitude: "115.9867", imageUrl: "/mountains/lushan.jpg"
  }
];
